#!/bin/sh

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn app server
# Description:       starts unicorn using start-stop-daemon
### END INIT INFO

set -e

USAGE="Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"

# app settings
TIMEOUT=${TIMEOUT-60}
APP_ROOT="/var/www/application/current"
APP_USER=deployuser
PID=$APP_ROOT/tmp/pids/unicorn.pid
ENV="production"

# environment settings
PATH="/home/$APP_USER/.rvm/gems/ruby-2.2.1/bin:/home/$APP_USER/.rvm/gems/ruby-2.2.1@global/bin:/home/$APP_USER/.rvm/rubies/ruby-2.2.1/bin:/home/$APP_USER/.rvm/bin:$PATH"
CMD="cd $APP_ROOT && source /home/$APP_USER/.rvm/scripts/rvm && bundle exec unicorn_rails -E $ENV -D -c $APP_ROOT/config/unicorn.rb"
action="$1"

set -u

old_pid="$PID.oldbin"

# make sure the app exists
cd $APP_ROOT || exit 1

sig () {
  test -s "$PID" && kill -$1 `cat $PID`
}

oldsig () {
  test -s $old_pid && kill -$1 `cat $old_pid`
}

case $1 in
  start)
    sig 0 && echo >&2 "Already running" && exit 0
    su --login $APP_USER -c "$CMD"
    ;;

  stop)
    sig QUIT && exit 0
    echo >&2 "Not running"
    ;;
  force-stop)
    sig TERM && exit 0
    echo >&2 "Not running"
    ;;
  restart|reload)
    sig USR2 && echo "reloaded OK" && exit 0
    echo >&2 "Couldn't reload, starting  '$CMD' instead"
    su --login $APP_USER -c "$CMD"
    ;;
  upgrade)
        if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
          then
          n=$TIMEOUT
          while test -s $old_pid && test $n -ge 0
            do
              printf '.' && sleep 1 && n=$(( $n - 1 ))
            done

          echo

          if test $n -lt 0 && test -s $old_pid
            then
            echo >&2 "$old_pid still exists after $TIMEOUT seconds"
            exit 1
          fi
          exit 0
        fi
        echo >&2 "Couldn't upgrade, starting '$CMD' instead"
        su --login $APP_USER -c "$CMD"
        ;;
  reopen-logs)
        sig USR1
        ;;
  *)
    echo >&2 "$USAGE: $0 "
    exit 1
    ;;
esac